#Can one block of except statements handle multiple exception?
'''
Yes, in Python, you can use a single except block to handle multiple
exceptions by listing them within parentheses after the except keyword
'''
